# Generated by Django 2.2.5 on 2019-11-13 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, default=None, max_digits=10)),
                ('lender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Lender', to=settings.AUTH_USER_MODEL)),
                ('ower', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Ower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
    ]
