# Generated by Django 2.2.5 on 2019-11-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='GroupModel',
        ),
    ]
